version: 0.1.1
default:
  # Default profile created for data IO access.
  # Add your credentials for the source you use, and delete the rest.

  # Google
  # GOOGLE_SERVICE_ACC_KEY:
  #   type: service_account
  #   project_id: project-id
  #   private_key_id: key-id
  #   private_key: "-----BEGIN PRIVATE KEY-----\nyour_private_key\n-----END_PRIVATE_KEY"
  #   client_email: your_service_account_email
  #   auth_uri: "https://accounts.google.com/o/oauth2/auth"
  #   token_uri: "https://accounts.google.com/o/oauth2/token"
  #   auth_provider_x509_cert_url: "https://www.googleapis.com/oauth2/v1/certs"
  #   client_x509_cert_url: "https://www.googleapis.com/robot/v1/metadata/x509/your_service_account_email"
  GOOGLE_SERVICE_ACC_KEY_FILEPATH: "{{ env_var('GOOGLE_SERVICE_ACC_KEY_FILEPATH', 'de_project/keys.json') }}"
  GOOGLE_LOCATION: US # Optional
